// <auto-generated />
using System;
using BibliospherePRAVI1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliospherePRAVI1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliospherePRAVI1.Models.Autor", b =>
                {
                    b.Property<int>("autorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("autorID"));

                    b.Property<DateTime>("autorDatumRod")
                        .HasColumnType("datetime2");

                    b.Property<string>("autorIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("autorPrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("autorSlika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("autorID");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Autor_Knjiga", b =>
                {
                    b.Property<int>("AutorID")
                        .HasColumnType("int");

                    b.Property<int>("KnjigaID")
                        .HasColumnType("int");

                    b.Property<int>("AutorKnjigaID")
                        .HasColumnType("int");

                    b.HasKey("AutorID", "KnjigaID");

                    b.HasIndex("KnjigaID");

                    b.ToTable("AutorKnjiga", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.GodisnjiIzvjestaj", b =>
                {
                    b.Property<int>("IzvjestajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvjestajID"));

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int>("najcitanijiZanr")
                        .HasColumnType("int");

                    b.HasKey("IzvjestajID");

                    b.HasIndex("korisnikID");

                    b.ToTable("GodisnjiIzvjestaji");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Izdavac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NazivIzdavaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Izdavac", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Knjiga", b =>
                {
                    b.Property<int>("knjigaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("knjigaID"));

                    b.Property<long>("ISBN")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datumObjavljivanjaKnj")
                        .HasColumnType("datetime2");

                    b.Property<int?>("izdavacID")
                        .HasColumnType("int");

                    b.Property<string>("knjigaBarKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("knjigaNaziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("knjigaSlika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int>("vrstaKnjige")
                        .HasColumnType("int");

                    b.HasKey("knjigaID");

                    b.HasIndex("izdavacID");

                    b.HasIndex("korisnikID");

                    b.ToTable("Knjiga", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.KnjigaKorisnik", b =>
                {
                    b.Property<int>("knjigaKorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("knjigaKorisnikID"));

                    b.Property<int?>("knjigaID")
                        .HasColumnType("int");

                    b.Property<int>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int>("vrstaListe")
                        .HasColumnType("int");

                    b.HasKey("knjigaKorisnikID");

                    b.HasIndex("knjigaID");

                    b.HasIndex("korisnikID");

                    b.ToTable("KnjigaKorisnik", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Korisnik", b =>
                {
                    b.Property<int>("korisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("korisnikID"));

                    b.Property<string>("brojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("citateljDatPrid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datumZaposlenjaAD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datumZaposlenjaKP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("korisnikDatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("korisnikEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("korisnikIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("korisnikLozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("korisnikPrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("korisnikUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("korisnikID");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.MjesecniIzvjestaj", b =>
                {
                    b.Property<int>("IzvjestajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvjestajID"));

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int>("najcitanijiZanr")
                        .HasColumnType("int");

                    b.HasKey("IzvjestajID");

                    b.HasIndex("korisnikID");

                    b.ToTable("MjesecniIzvjestaji");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Recenzija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("KnjigaID")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnikID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Ocjena")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("KnjigaID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Recenzija", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.SedmicniIzvjestaj", b =>
                {
                    b.Property<int>("IzvjestajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvjestajID"));

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int>("najcitanijiZanr")
                        .HasColumnType("int");

                    b.HasKey("IzvjestajID");

                    b.HasIndex("korisnikID");

                    b.ToTable("SedmicniIzvjestaji");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Autor_Knjiga", b =>
                {
                    b.HasOne("BibliospherePRAVI1.Models.Autor", "Autor")
                        .WithMany("AutorKnjiga")
                        .HasForeignKey("AutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliospherePRAVI1.Models.Knjiga", "Knjiga")
                        .WithMany("AutorKnjiga")
                        .HasForeignKey("KnjigaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Knjiga");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.GodisnjiIzvjestaj", b =>
                {
                    b.HasOne("BibliospherePRAVI1.Models.Korisnik", "korisnik")
                        .WithMany()
                        .HasForeignKey("korisnikID");

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Knjiga", b =>
                {
                    b.HasOne("BibliospherePRAVI1.Models.Izdavac", "izdavac")
                        .WithMany()
                        .HasForeignKey("izdavacID");

                    b.HasOne("BibliospherePRAVI1.Models.Korisnik", null)
                        .WithMany("listaKnjiga")
                        .HasForeignKey("korisnikID");

                    b.Navigation("izdavac");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.KnjigaKorisnik", b =>
                {
                    b.HasOne("BibliospherePRAVI1.Models.Knjiga", "knjiga")
                        .WithMany()
                        .HasForeignKey("knjigaID");

                    b.HasOne("BibliospherePRAVI1.Models.Korisnik", "korisnik")
                        .WithMany("knjigaKorisnik")
                        .HasForeignKey("korisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("knjiga");

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.MjesecniIzvjestaj", b =>
                {
                    b.HasOne("BibliospherePRAVI1.Models.Korisnik", "korisnik")
                        .WithMany()
                        .HasForeignKey("korisnikID");

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Recenzija", b =>
                {
                    b.HasOne("BibliospherePRAVI1.Models.Knjiga", "knjiga")
                        .WithMany("Recenzije")
                        .HasForeignKey("KnjigaID");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID");

                    b.Navigation("knjiga");

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.SedmicniIzvjestaj", b =>
                {
                    b.HasOne("BibliospherePRAVI1.Models.Korisnik", "korisnik")
                        .WithMany()
                        .HasForeignKey("korisnikID");

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Autor", b =>
                {
                    b.Navigation("AutorKnjiga");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Knjiga", b =>
                {
                    b.Navigation("AutorKnjiga");

                    b.Navigation("Recenzije");
                });

            modelBuilder.Entity("BibliospherePRAVI1.Models.Korisnik", b =>
                {
                    b.Navigation("knjigaKorisnik");

                    b.Navigation("listaKnjiga");
                });
#pragma warning restore 612, 618
        }
    }
}
